`timescale 1ns/1ps

module priority_encoder4to2_tb;

reg  [3:0] d;
wire [1:0] y;
wire valid;

// Instantiate DUT
priority_encoder4to2 dut (
    .d(d),
    .y(y),
    .valid(valid)
);

initial begin
    // Generate waveform
    $dumpfile("priority_encoder4to2.vcd");
    $dumpvars(0, priority_encoder4to2_tb);

    $monitor("%4t\t%b\t%b\t%b", $time, d, y, valid);

    d = 4'b0000; #10;
    d = 4'b0001; #10;
    d = 4'b0010; #10;
    d = 4'b0100; #10;
    d = 4'b1000; #10;
    d = 4'b0011; #10;
    d = 4'b0110; #10;
    d = 4'b1111; #10;
    d = 4'b1010; #10;
    d = 4'b0101; #10;

    #10;
    $finish;
end

endmodule